### ISSUE TITLE
pip hanging when trying to resolve dependencies

### ISSUE THREAD

**Issue by rnfinnegan** [pyplati/platipy#115]
When installing `platipy` using `pip install platipy`, the install will hang indefinitely due to the built-in conflict resolver in pip.

**Comment by karllandheer** [comment]
I also have had this issue. Does anyone know the solution to this?

**Comment by pchlap** [comment]
Hi @karllandheer,

one thing to try first it to update pip. I noticed that this issue seemed to often be resolved on the newer versions of pip.

`pip install --upgrade pip`

If the issue persists, let me know what pip version you are using as well as which OS and Python version.

**Comment by karllandheer** [comment]
Hello, thank you for your comment. This did resolve the issue for me.

**Comment by pchlap** [comment]
> I am experiencing this same problem in Google Colab running any of the platipy notebooks. Installed pip version is 21.1, using pip install --upgrade pip - upgrades to pip version 22.1
> 
> Using [examples/visualise.ipynb](https://github.com/pyplati/platipy/blob/9bdfe1b994b330d2ab747b64227db0abecdc2bb3/examples/visualise.ipynb)
> 
> ```
> try:
>     import platipy
> except:
>     !pip install git+https://github.com/pyplati/platipy.git
>     import platipy
> ```
> 
> [colab-platipy-install-log.txt](https://github.com/pyplati/platipy/files/8689581/colab-platipy-install-log.txt)
> 
> From the logs (attached), a significant amount of time is spent downloading multiple versions of the same dependency
> 
> * idna<4,>=2.5
> * certifi>=2017.4.17
> * charset-normalizer~=2.0.0
> * pytz>=2017.3
> 
> I get the same behavior using `pip install -U platipy` and `pip install platipy`
> 
> So far, after 24 hours using a default Google Colab notebook, platipy has still not completed install.

Hi @thomasjtaylor, apologies for the slow reply here... This is a real head scratcher, I don't know why this is happening...

There is workaround for now, but it isn't ideal... In colab, upgrade pip, the reinstall platipy:
```python
!pip install --upgrade pip
!pip install platipy
```

You may still get an error, but if you then restart your runtime (Runtime->Restart Runtime), then run from the top again it should work. Not ideal I know, but a workaround for now.

Moving forward we'll be reworking the dependency management in platipy entirely using a tool called poetry. I'm just waiting for poetry 1.2 to land since that has some key features we'll make use of and hopefully all these issues will be resolved after that's done.

**Comment by pchlap** [comment]
Migration to poetry is now complete and platipy 0.5.0 seems the have resolved this problem. Please let us know if this issue reappears anywhere again.
