### ISSUE TITLE
Contours displayed are slightly off compared to original mask

### ISSUE THREAD

**Issue by NBarryMedPhys** [pyplati/platipy#147]
When a contour is generated from a SimpleITK image mask it seems to be slightly off when visually inspected.

Some examples are shown below with the example data provided with PlatiPy. I have used add_scalar_overlay to quickly display the corresponding mask.

Thanks!
Nathaniel

![plati](https://user-images.githubusercontent.com/91929554/177697509-37cf4aa1-dbb4-49dc-a06a-798a4e6920e9.PNG)
![pltip2](https://user-images.githubusercontent.com/91929554/177697517-847f15f5-022c-4dec-bd04-f4db8fc4906b.PNG)
![plat3](https://user-images.githubusercontent.com/91929554/177697521-8019f7cd-3407-4466-af87-8323e48e49e4.PNG)

**Comment by rnfinnegan** [comment]
Thanks for raising this issue @NBarryMedPhys!

It was a result of `matplotlib` default behaviour - although honestly I can't be sure of the exact cause.

I have found a solution by specifying the `extent` of the contour and image, which seems to work. See plots below.

Some additional testing is required, but we will keep this issue open until the fix is merged through in a new release.

Cheers,
Rob

Original behaviour: 
![image](https://user-images.githubusercontent.com/16299474/179137801-bb4f2459-a0f7-49d5-b7d9-4370adb7f4a1.png)

New behaviour:
![image](https://user-images.githubusercontent.com/16299474/179138133-83319d42-55c2-4235-9d92-e2272977d0f1.png)

**Comment by NBarryMedPhys** [comment]
Big thanks for looking into this issue, it's much appreciated!

**Comment by pchlap** [comment]
Hi @NBarryMedPhys, with the release of platipy 0.5.0 this issue should be resolved. I'll close this for now but please let us know if you notice this issue after upgrading. Thanks a lot for the bug report!
