### ISSUE TITLE
image registration check raises exception

### ISSUE THREAD

**Issue by bwheelz36** [pyplati/platipy#238]
Hey, I wanted to check the image registration functionality. 

- I tried Bsplines with the script below, and got `ITK ERROR: ResampleImageFilter(000001848246B530): Interpolator not set`
- The data I used is from [synthRad](https://zenodo.org/records/7260705) and can be publicly downloaded 

Weirdly, if I comment out [this `SetInterpolator` line](https://github.com/pyplati/platipy/blob/9b82dcc5a6fb33ea98e4b1e1c078653303406bc2/platipy/imaging/registration/utils.py#L187) the code runs. If I change interpolation order from the platipy default (3) to the SITK default (2) the code runs...

```python
from pathlib import Path
from platipy.imaging.registration import deformable as df
import SimpleITK as sitk

fixed_image_loc = Path(r'X:\SynthRadChallenge\brain\2BA001\cbct.nii.gz')
moving_image_loc = Path(r'X:\SynthRadChallenge\brain\2BA002\ct.nii.gz')

assert fixed_image_loc.is_file()
assert moving_image_loc.is_file()

fixed_image = sitk.ReadImage(fixed_image_loc)
moving_image = sitk.ReadImage(moving_image_loc)

registered_image, output_transform = df.bspline_registration(fixed_image, moving_image, ncores=4)
```

**Comment by pchlap** [comment]
Hi @bwheelz36, thanks for reporting this. I imagine this is due to a new SimpleITK version. Seems like we have been discovering a few breaking changes since SimpleITK 2.3.0.

I will look into this and hopefully can rectify the issue. Thanks.

**Comment by rnfinnegan** [comment]
Hi @bwheelz36 and @pchlap - yes I believe this is due to a change in SimpleITK versions.

Previously, `sitk.sitkBSpline` was equal to `3` (see [SimpleITK v2.1.0 code](https://github.com/SimpleITK/SimpleITK/blob/v2.1.0/Code/Common/include/sitkInterpolator.h))

Now, `sitk.sitkBSpline` is equal to `23` (see [SimpleITK v2.3.0 code](https://github.com/SimpleITK/SimpleITK/blob/v2.3.0/Code/Common/include/sitkInterpolator.h))

I'm not sure why this has changed, but if we change the default interpolation in the BSplines registration code to `sitk.sitkBSpline` (rather than the actual integer value `3`) this should solve the problem. In the meantime, you could also run the last line of code as:
```
registered_image, output_transform = df.bspline_registration(fixed_image, moving_image, ncores=4, interp_order=sitk.sitkBSpline)
```

**Comment by bwheelz36** [comment]
guys, your library is really well written and helpful - thanks! it's nice just to see all the options cleanly documented, i'm struggling with the sitk docs.
